-   id: check-readme
    name: check-readme
    description: 'Check for README file'
    entry: python check-readme.py
    language: python
    types: [python]
    additional_dependencies: []
    minimum_pre_commit_version: '2.9.2'
